


//FILE GENERATED BY A TOOL


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;

using UHub.CoreLib.Extensions;
using UHub.CoreLib.DataInterop;
using UHub.CoreLib.Attributes;



namespace UHub.CoreLib.Entities.Users
{
    ///<summary>
    ///AutoGenerated DataConverters for User
    ///</summary>
    partial class User
    {

        /// <summary>
        /// Convert DataRow to User
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new User();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.IsConfirmed = row.Field<System.Boolean>("IsConfirmed");
            obj.IsApproved = row.Field<System.Boolean>("IsApproved");
            obj.Version = row.Field<System.String>("Version");
            obj.IsAdmin = row.Field<System.Boolean>("IsAdmin");
            obj.Email = row.Field<System.String>("Email");
            obj.Username = row.Field<System.String>("Username");
            obj.Name = row.Field<System.String>("Name");
            obj.PhoneNumber = row.Field<System.String>("PhoneNumber");
            obj.Major = row.Field<System.String>("Major");
            obj.Year = row.Field<System.String>("Year");
            obj.GradDate = row.Field<System.String>("GradDate");
            obj.Company = row.Field<System.String>("Company");
            obj.JobTitle = row.Field<System.String>("JobTitle");
            obj.IsFinished = row.Field<System.Boolean>("IsFinished");
            obj.SchoolID = row.Field<System.Int64?>("SchoolID");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to User
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new User();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.IsConfirmed = (System.Boolean)reader["IsConfirmed"];
            obj.IsApproved = (System.Boolean)reader["IsApproved"];
            obj.Version = reader["Version"] as System.String;
            obj.IsAdmin = (System.Boolean)reader["IsAdmin"];
            obj.Email = reader["Email"] as System.String;
            obj.Username = reader["Username"] as System.String;
            obj.Name = reader["Name"] as System.String;
            obj.PhoneNumber = reader["PhoneNumber"] as System.String;
            obj.Major = reader["Major"] as System.String;
            obj.Year = reader["Year"] as System.String;
            obj.GradDate = reader["GradDate"] as System.String;
            obj.Company = reader["Company"] as System.String;
            obj.JobTitle = reader["JobTitle"] as System.String;
            obj.IsFinished = (System.Boolean)reader["IsFinished"];
            if (reader["SchoolID"] != DBNull.Value)
            {
                obj.SchoolID = (System.Int64)reader["SchoolID"];
            }
            else
            {
                obj.SchoolID = null;
            }
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }


    ///<summary>
    ///AutoGenerated DataConverters for UserRecoveryContext
    ///</summary>
    partial class UserRecoveryContext
    {

        /// <summary>
        /// Convert DataRow to UserRecoveryContext
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserRecoveryContext(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new UserRecoveryContext();
            obj.UserID = row.Field<System.Int64>("UserID");
            obj.RecoveryID = row.Field<System.String>("RecoveryID");
            obj.RecoveryKey = row.Field<System.String>("RecoveryKey");
            obj.EffFromDate = row.Field<System.DateTimeOffset>("EffFromDate");
            obj.EffToDate = row.Field<System.DateTimeOffset>("EffToDate");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.AttemptCount = row.Field<System.Byte>("AttemptCount");
            obj.IsOptional = row.Field<System.Boolean>("IsOptional");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to UserRecoveryContext
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserRecoveryContext(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new UserRecoveryContext();

            obj.UserID = (System.Int64)reader["UserID"];
            obj.RecoveryID = reader["RecoveryID"] as System.String;
            obj.RecoveryKey = reader["RecoveryKey"] as System.String;
            obj.EffFromDate = (System.DateTimeOffset)reader["EffFromDate"];
            obj.EffToDate = (System.DateTimeOffset)reader["EffToDate"];
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.AttemptCount = (System.Byte)reader["AttemptCount"];
            obj.IsOptional = (System.Boolean)reader["IsOptional"]; return obj;
        }
    }


    ///<summary>
    ///AutoGenerated DataConverters for UserConfirmToken
    ///</summary>
    partial class UserConfirmToken
    {

        /// <summary>
        /// Convert DataRow to UserConfirmToken
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserConfirmToken(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new UserConfirmToken();
            obj.UserID = row.Field<System.Int64>("UserID");
            obj.RefUID = row.Field<System.String>("RefUID");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ConfirmedDate = row.Field<System.DateTimeOffset?>("ConfirmedDate");
            obj.IsConfirmed = row.Field<System.Boolean>("IsConfirmed");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to UserConfirmToken
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserConfirmToken(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new UserConfirmToken();

            obj.UserID = (System.Int64)reader["UserID"];
            obj.RefUID = reader["RefUID"] as System.String;
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ConfirmedDate"] != DBNull.Value)
            {
                obj.ConfirmedDate = (System.DateTimeOffset)reader["ConfirmedDate"];
            }
            else
            {
                obj.ConfirmedDate = null;
            }
            obj.IsConfirmed = (System.Boolean)reader["IsConfirmed"];
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"]; return obj;
        }
    }


    ///<summary>
    ///AutoGenerated DataConverters for UserAuthData
    ///</summary>
    partial class UserAuthData
    {

        /// <summary>
        /// Convert DataRow to UserAuthData
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserAuthData(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new UserAuthData();
            obj.UserID = row.Field<System.Int64>("UserID");
            obj.PswdHash = row.Field<System.String>("PswdHash");
            obj.Salt = row.Field<System.String>("Salt");
            obj.PswdCreatedDate = row.Field<System.DateTimeOffset>("PswdCreatedDate");
            obj.PswdModifiedDate = row.Field<System.DateTimeOffset>("PswdModifiedDate");
            obj.LastLockoutDate = row.Field<System.DateTimeOffset?>("LastLockoutDate");
            obj.StartFailedPswdWindow = row.Field<System.DateTimeOffset?>("StartFailedPswdWindow");
            obj.FailedPswdAttemptCount = row.Field<System.Byte>("FailedPswdAttemptCount");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to UserAuthData
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Users.UserAuthData(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new UserAuthData();

            obj.UserID = (System.Int64)reader["UserID"];
            obj.PswdHash = reader["PswdHash"] as System.String;
            obj.Salt = reader["Salt"] as System.String;
            obj.PswdCreatedDate = (System.DateTimeOffset)reader["PswdCreatedDate"];
            obj.PswdModifiedDate = (System.DateTimeOffset)reader["PswdModifiedDate"];
            if (reader["LastLockoutDate"] != DBNull.Value)
            {
                obj.LastLockoutDate = (System.DateTimeOffset)reader["LastLockoutDate"];
            }
            else
            {
                obj.LastLockoutDate = null;
            }
            if (reader["StartFailedPswdWindow"] != DBNull.Value)
            {
                obj.StartFailedPswdWindow = (System.DateTimeOffset)reader["StartFailedPswdWindow"];
            }
            else
            {
                obj.StartFailedPswdWindow = null;
            }
            obj.FailedPswdAttemptCount = (System.Byte)reader["FailedPswdAttemptCount"]; return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.Schools
{
    ///<summary>
    ///AutoGenerated DataConverters for School
    ///</summary>
    partial class School
    {

        /// <summary>
        /// Convert DataRow to School
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Schools.School(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new School();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.Name = row.Field<System.String>("Name");
            obj.State = row.Field<System.String>("State");
            obj.City = row.Field<System.String>("City");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Description = row.Field<System.String>("Description");
            obj.DomainValidator = row.Field<System.String>("DomainValidator");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to School
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Schools.School(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new School();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.Name = reader["Name"] as System.String;
            obj.State = reader["State"] as System.String;
            obj.City = reader["City"] as System.String;
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Description = reader["Description"] as System.String;
            obj.DomainValidator = reader["DomainValidator"] as System.String;
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.SchoolMajors
{
    ///<summary>
    ///AutoGenerated DataConverters for SchoolMajor
    ///</summary>
    partial class SchoolMajor
    {

        /// <summary>
        /// Convert DataRow to SchoolMajor
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.SchoolMajors.SchoolMajor(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new SchoolMajor();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.Name = row.Field<System.String>("Name");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadonly = row.Field<System.Boolean>("IsReadonly");
            obj.Description = row.Field<System.String>("Description");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to SchoolMajor
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.SchoolMajors.SchoolMajor(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new SchoolMajor();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.Name = reader["Name"] as System.String;
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadonly = (System.Boolean)reader["IsReadonly"];
            obj.Description = reader["Description"] as System.String;
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.SchoolClubs
{
    ///<summary>
    ///AutoGenerated DataConverters for SchoolClub
    ///</summary>
    partial class SchoolClub
    {

        /// <summary>
        /// Convert DataRow to SchoolClub
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.SchoolClubs.SchoolClub(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new SchoolClub();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Name = row.Field<System.String>("Name");
            obj.Description = row.Field<System.String>("Description");
            obj.SchoolID = row.Field<System.Int64>("SchoolID");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to SchoolClub
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.SchoolClubs.SchoolClub(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new SchoolClub();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Name = reader["Name"] as System.String;
            obj.Description = reader["Description"] as System.String;
            obj.SchoolID = (System.Int64)reader["SchoolID"];
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.ClubModerators
{
    ///<summary>
    ///AutoGenerated DataConverters for ClubModerator
    ///</summary>
    partial class ClubModerator
    {

        /// <summary>
        /// Convert DataRow to ClubModerator
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.ClubModerators.ClubModerator(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new ClubModerator();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.UserID = row.Field<System.Int64>("UserID");
            obj.IsOwner = row.Field<System.Boolean>("IsOwner");
            obj.IsValid = row.Field<System.Boolean>("IsValid");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to ClubModerator
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.ClubModerators.ClubModerator(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new ClubModerator();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.UserID = (System.Int64)reader["UserID"];
            obj.IsOwner = (System.Boolean)reader["IsOwner"];
            obj.IsValid = (System.Boolean)reader["IsValid"];
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.Posts
{
    ///<summary>
    ///AutoGenerated DataConverters for Post
    ///</summary>
    partial class Post
    {

        /// <summary>
        /// Convert DataRow to Post
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Posts.Post(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new Post();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Name = row.Field<System.String>("Name");
            obj.Content = row.Field<System.String>("Content");
            obj.IsModified = row.Field<System.Boolean>("IsModified");
            obj.ViewCount = row.Field<System.Int64>("ViewCount");
            obj.IsLocked = row.Field<System.Boolean>("IsLocked");
            obj.CanComment = row.Field<System.Boolean>("CanComment");
            obj.IsPublic = row.Field<System.Boolean>("IsPublic");
            obj.ParentID = row.Field<System.Int64>("ParentID");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to Post
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Posts.Post(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new Post();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Name = reader["Name"] as System.String;
            obj.Content = reader["Content"] as System.String;
            obj.IsModified = (System.Boolean)reader["IsModified"];
            obj.ViewCount = (System.Int64)reader["ViewCount"];
            obj.IsLocked = (System.Boolean)reader["IsLocked"];
            obj.CanComment = (System.Boolean)reader["CanComment"];
            obj.IsPublic = (System.Boolean)reader["IsPublic"];
            obj.ParentID = (System.Int64)reader["ParentID"];
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }


    ///<summary>
    ///AutoGenerated DataConverters for PostClusteredCount
    ///</summary>
    partial class PostClusteredCount
    {

        /// <summary>
        /// Convert DataRow to PostClusteredCount
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Posts.PostClusteredCount(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new PostClusteredCount();
            obj.SchoolID = row.Field<System.Int64>("SchoolID");
            obj.SchoolClubID = row.Field<System.Int64?>("SchoolClubID");
            obj.PublicPostCount = row.Field<System.Int64>("PublicPostCount");
            obj.PrivatePostCount = row.Field<System.Int64>("PrivatePostCount");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to PostClusteredCount
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Posts.PostClusteredCount(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new PostClusteredCount();

            obj.SchoolID = (System.Int64)reader["SchoolID"];
            if (reader["SchoolClubID"] != DBNull.Value)
            {
                obj.SchoolClubID = (System.Int64)reader["SchoolClubID"];
            }
            else
            {
                obj.SchoolClubID = null;
            }
            obj.PublicPostCount = (System.Int64)reader["PublicPostCount"];
            obj.PrivatePostCount = (System.Int64)reader["PrivatePostCount"]; return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.Comments
{
    ///<summary>
    ///AutoGenerated DataConverters for Comment
    ///</summary>
    partial class Comment
    {

        /// <summary>
        /// Convert DataRow to Comment
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Comments.Comment(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new Comment();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Content = row.Field<System.String>("Content");
            obj.IsModified = row.Field<System.Boolean>("IsModified");
            obj.ViewCount = row.Field<System.Int64>("ViewCount");
            obj.ParentID = row.Field<System.Int64>("ParentID");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to Comment
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Comments.Comment(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new Comment();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Content = reader["Content"] as System.String;
            obj.IsModified = (System.Boolean)reader["IsModified"];
            obj.ViewCount = (System.Int64)reader["ViewCount"];
            obj.ParentID = (System.Int64)reader["ParentID"];
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.Files
{
    ///<summary>
    ///AutoGenerated DataConverters for File
    ///</summary>
    partial class File
    {

        /// <summary>
        /// Convert DataRow to File
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Files.File(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new File();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Name = row.Field<System.String>("Name");
            obj.ViewCount = row.Field<System.Int64>("ViewCount");
            obj.FilePath = row.Field<System.String>("FilePath");
            obj.Description = row.Field<System.String>("Description");
            obj.FileHash_SHA256 = row.Field<System.String>("FileHash_SHA256");
            obj.SourceName = row.Field<System.String>("SourceName");
            obj.SourceType = row.Field<System.String>("SourceType");
            obj.DownloadName = row.Field<System.String>("DownloadName");
            obj.ParentID = row.Field<System.String>("ParentID");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to File
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Files.File(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new File();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Name = reader["Name"] as System.String;
            obj.ViewCount = (System.Int64)reader["ViewCount"];
            obj.FilePath = reader["FilePath"] as System.String;
            obj.Description = reader["Description"] as System.String;
            obj.FileHash_SHA256 = reader["FileHash_SHA256"] as System.String;
            obj.SourceName = reader["SourceName"] as System.String;
            obj.SourceType = reader["SourceType"] as System.String;
            obj.DownloadName = reader["DownloadName"] as System.String;
            obj.ParentID = reader["ParentID"] as System.String;
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Entities.Images
{
    ///<summary>
    ///AutoGenerated DataConverters for Image
    ///</summary>
    partial class Image
    {

        /// <summary>
        /// Convert DataRow to Image
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Entities.Images.Image(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new Image();
            obj.ID = row.Field<System.Int64?>("ID");
            obj.IsEnabled = row.Field<System.Boolean>("IsEnabled");
            obj.IsReadOnly = row.Field<System.Boolean>("IsReadOnly");
            obj.Name = row.Field<System.String>("Name");
            obj.ViewCount = row.Field<System.Int64>("ViewCount");
            obj.FilePath = row.Field<System.String>("FilePath");
            obj.Description = row.Field<System.String>("Description");
            obj.FileHash_SHA256 = row.Field<System.String>("FileHash_SHA256");
            obj.SourceName = row.Field<System.String>("SourceName");
            obj.SourceType = row.Field<System.String>("SourceType");
            obj.DownloadName = row.Field<System.String>("DownloadName");
            obj.ParentID = row.Field<System.String>("ParentID");
            obj.IsDeleted = row.Field<System.Boolean>("IsDeleted");
            obj.CreatedBy = row.Field<System.Int64>("CreatedBy");
            obj.CreatedDate = row.Field<System.DateTimeOffset>("CreatedDate");
            obj.ModifiedBy = row.Field<System.Int64?>("ModifiedBy");
            obj.ModifiedDate = row.Field<System.DateTimeOffset?>("ModifiedDate");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to Image
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Entities.Images.Image(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new Image();

            if (reader["ID"] != DBNull.Value)
            {
                obj.ID = (System.Int64)reader["ID"];
            }
            else
            {
                obj.ID = null;
            }
            obj.IsEnabled = (System.Boolean)reader["IsEnabled"];
            obj.IsReadOnly = (System.Boolean)reader["IsReadOnly"];
            obj.Name = reader["Name"] as System.String;
            obj.ViewCount = (System.Int64)reader["ViewCount"];
            obj.FilePath = reader["FilePath"] as System.String;
            obj.Description = reader["Description"] as System.String;
            obj.FileHash_SHA256 = reader["FileHash_SHA256"] as System.String;
            obj.SourceName = reader["SourceName"] as System.String;
            obj.SourceType = reader["SourceType"] as System.String;
            obj.DownloadName = reader["DownloadName"] as System.String;
            obj.ParentID = reader["ParentID"] as System.String;
            obj.IsDeleted = (System.Boolean)reader["IsDeleted"];
            obj.CreatedBy = (System.Int64)reader["CreatedBy"];
            obj.CreatedDate = (System.DateTimeOffset)reader["CreatedDate"];
            if (reader["ModifiedBy"] != DBNull.Value)
            {
                obj.ModifiedBy = (System.Int64)reader["ModifiedBy"];
            }
            else
            {
                obj.ModifiedBy = null;
            }
            if (reader["ModifiedDate"] != DBNull.Value)
            {
                obj.ModifiedDate = (System.DateTimeOffset)reader["ModifiedDate"];
            }
            else
            {
                obj.ModifiedDate = null;
            }
            return obj;
        }
    }

}

namespace UHub.CoreLib.Security.Authentication
{
    ///<summary>
    ///AutoGenerated DataConverters for TokenValidator
    ///</summary>
    partial class TokenValidator
    {

        /// <summary>
        /// Convert DataRow to TokenValidator
        /// </summary>
        /// <param name="row">The DataRow that will be converted into an object</param>
        public static explicit operator UHub.CoreLib.Security.Authentication.TokenValidator(DataRow row)
        {
            var columnSet = row.Table.Columns;
            var obj = new TokenValidator();
            obj.IssueDate = row.Field<System.DateTimeOffset>("IssueDate");
            obj.MaxExpirationDate = row.Field<System.DateTimeOffset>("MaxExpirationDate");
            obj.TokenID = row.Field<System.String>("TokenID");
            obj.IsPersistent = row.Field<System.Boolean>("IsPersistent");
            obj.TokenHash = row.Field<System.String>("TokenHash");
            obj.RequestID = row.Field<System.String>("RequestID");
            obj.SessionID = row.Field<System.String>("SessionID");
            obj.IsValid = row.Field<System.Boolean>("IsValid");
            return obj;
        }

        ///<summary>
        ///Convert SqlDataReader to TokenValidator
        ///</summary>
        /// <param name="reader">The SqlDataReader that is streaming the dataset to be converted.  With convert the row at the current iterator position</param>
        public static explicit operator UHub.CoreLib.Security.Authentication.TokenValidator(SqlDataReader reader)
        {
            var columnSet = reader.GetSchemaTable().Columns;
            var obj = new TokenValidator();

            obj.IssueDate = (System.DateTimeOffset)reader["IssueDate"];
            obj.MaxExpirationDate = (System.DateTimeOffset)reader["MaxExpirationDate"];
            obj.TokenID = reader["TokenID"] as System.String;
            obj.IsPersistent = (System.Boolean)reader["IsPersistent"];
            obj.TokenHash = reader["TokenHash"] as System.String;
            obj.RequestID = reader["RequestID"] as System.String;
            obj.SessionID = reader["SessionID"] as System.String;
            obj.IsValid = (System.Boolean)reader["IsValid"]; return obj;
        }
    }

}

