


//FILE GENERATED BY A TOOL


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;

using UHub.CoreLib.Extensions;
using UHub.CoreLib.DataInterop;
using UHub.CoreLib.Attributes;



namespace UHub.CoreLib.Entities.Users.DTOs
{
    ///<summary>
    ///AutoGenerated DataConverters for User_R_PrivateDTO
    ///</summary>
    partial class User_R_PrivateDTO
    {

        /// <summary>
        /// Convert User to User_R_PrivateDTO
        /// </summary>
        /// <param name="arg1">The User that will be converted into an User_R_PrivateDTO</param>
        public static explicit operator UHub.CoreLib.Entities.Users.DTOs.User_R_PrivateDTO(UHub.CoreLib.Entities.Users.User dtoObj)
        {
            UHub.CoreLib.Entities.Users.DTOs.User_R_PrivateDTO nativeObj = new UHub.CoreLib.Entities.Users.DTOs.User_R_PrivateDTO();

            nativeObj.Email = dtoObj.Email;
            nativeObj.Name = dtoObj.Name;
            nativeObj.PhoneNumber = dtoObj.PhoneNumber;
            nativeObj.SchoolID = dtoObj.SchoolID;
            nativeObj.Username = dtoObj.Username;
            nativeObj.Major = dtoObj.Major;
            nativeObj.Year = dtoObj.Year;
            nativeObj.GradDate = dtoObj.GradDate;
            nativeObj.Company = dtoObj.Company;
            nativeObj.JobTitle = dtoObj.JobTitle;
            return nativeObj;
        }


        /// <summary>
        /// Convert User_R_PrivateDTO to User
        /// </summary>
        /// <param name="arg1">The User_R_PrivateDTO that will be converted into an UHub.CoreLib.Entities.Users.User</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(UHub.CoreLib.Entities.Users.DTOs.User_R_PrivateDTO nativeObj)
        {
            UHub.CoreLib.Entities.Users.User dtoObj = new UHub.CoreLib.Entities.Users.User();

            dtoObj.Email = nativeObj.Email;
            dtoObj.Name = nativeObj.Name;
            dtoObj.PhoneNumber = nativeObj.PhoneNumber;
            dtoObj.SchoolID = nativeObj.SchoolID;
            dtoObj.Username = nativeObj.Username;
            dtoObj.Major = nativeObj.Major;
            dtoObj.Year = nativeObj.Year;
            dtoObj.GradDate = nativeObj.GradDate;
            dtoObj.Company = nativeObj.Company;
            dtoObj.JobTitle = nativeObj.JobTitle;
            return dtoObj;
        }
    }



    ///<summary>
    ///AutoGenerated DataConverters for User_R_PublicDTO
    ///</summary>
    partial class User_R_PublicDTO
    {

        /// <summary>
        /// Convert User to User_R_PublicDTO
        /// </summary>
        /// <param name="arg1">The User that will be converted into an User_R_PublicDTO</param>
        public static explicit operator UHub.CoreLib.Entities.Users.DTOs.User_R_PublicDTO(UHub.CoreLib.Entities.Users.User dtoObj)
        {
            UHub.CoreLib.Entities.Users.DTOs.User_R_PublicDTO nativeObj = new UHub.CoreLib.Entities.Users.DTOs.User_R_PublicDTO();

            nativeObj.Username = dtoObj.Username;
            nativeObj.Major = dtoObj.Major;
            nativeObj.Year = dtoObj.Year;
            nativeObj.GradDate = dtoObj.GradDate;
            nativeObj.Company = dtoObj.Company;
            nativeObj.JobTitle = dtoObj.JobTitle;
            return nativeObj;
        }


        /// <summary>
        /// Convert User_R_PublicDTO to User
        /// </summary>
        /// <param name="arg1">The User_R_PublicDTO that will be converted into an UHub.CoreLib.Entities.Users.User</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(UHub.CoreLib.Entities.Users.DTOs.User_R_PublicDTO nativeObj)
        {
            UHub.CoreLib.Entities.Users.User dtoObj = new UHub.CoreLib.Entities.Users.User();

            dtoObj.Username = nativeObj.Username;
            dtoObj.Major = nativeObj.Major;
            dtoObj.Year = nativeObj.Year;
            dtoObj.GradDate = nativeObj.GradDate;
            dtoObj.Company = nativeObj.Company;
            dtoObj.JobTitle = nativeObj.JobTitle;
            return dtoObj;
        }
    }



    ///<summary>
    ///AutoGenerated DataConverters for User_U_PrivateDTO
    ///</summary>
    partial class User_U_PrivateDTO
    {

        /// <summary>
        /// Convert User to User_U_PrivateDTO
        /// </summary>
        /// <param name="arg1">The User that will be converted into an User_U_PrivateDTO</param>
        public static explicit operator UHub.CoreLib.Entities.Users.DTOs.User_U_PrivateDTO(UHub.CoreLib.Entities.Users.User dtoObj)
        {
            UHub.CoreLib.Entities.Users.DTOs.User_U_PrivateDTO nativeObj = new UHub.CoreLib.Entities.Users.DTOs.User_U_PrivateDTO();

            nativeObj.ID = dtoObj.ID;
            nativeObj.Name = dtoObj.Name;
            nativeObj.PhoneNumber = dtoObj.PhoneNumber;
            nativeObj.Major = dtoObj.Major;
            nativeObj.Year = dtoObj.Year;
            nativeObj.GradDate = dtoObj.GradDate;
            nativeObj.Company = dtoObj.Company;
            nativeObj.JobTitle = dtoObj.JobTitle;
            return nativeObj;
        }


        /// <summary>
        /// Convert User_U_PrivateDTO to User
        /// </summary>
        /// <param name="arg1">The User_U_PrivateDTO that will be converted into an UHub.CoreLib.Entities.Users.User</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(UHub.CoreLib.Entities.Users.DTOs.User_U_PrivateDTO nativeObj)
        {
            UHub.CoreLib.Entities.Users.User dtoObj = new UHub.CoreLib.Entities.Users.User();

            dtoObj.ID = nativeObj.ID;
            dtoObj.Name = nativeObj.Name;
            dtoObj.PhoneNumber = nativeObj.PhoneNumber;
            dtoObj.Major = nativeObj.Major;
            dtoObj.Year = nativeObj.Year;
            dtoObj.GradDate = nativeObj.GradDate;
            dtoObj.Company = nativeObj.Company;
            dtoObj.JobTitle = nativeObj.JobTitle;
            return dtoObj;
        }
    }



    ///<summary>
    ///AutoGenerated DataConverters for User_C_PublicDTO
    ///</summary>
    partial class User_C_PublicDTO
    {

        /// <summary>
        /// Convert User to User_C_PublicDTO
        /// </summary>
        /// <param name="arg1">The User that will be converted into an User_C_PublicDTO</param>
        public static explicit operator UHub.CoreLib.Entities.Users.DTOs.User_C_PublicDTO(UHub.CoreLib.Entities.Users.User dtoObj)
        {
            UHub.CoreLib.Entities.Users.DTOs.User_C_PublicDTO nativeObj = new UHub.CoreLib.Entities.Users.DTOs.User_C_PublicDTO();

            nativeObj.Email = dtoObj.Email;
            nativeObj.Username = dtoObj.Username;
            nativeObj.Password = dtoObj.Password;
            nativeObj.Name = dtoObj.Name;
            nativeObj.PhoneNumber = dtoObj.PhoneNumber;
            nativeObj.Major = dtoObj.Major;
            nativeObj.Year = dtoObj.Year;
            nativeObj.GradDate = dtoObj.GradDate;
            nativeObj.Company = dtoObj.Company;
            nativeObj.JobTitle = dtoObj.JobTitle;
            return nativeObj;
        }


        /// <summary>
        /// Convert User_C_PublicDTO to User
        /// </summary>
        /// <param name="arg1">The User_C_PublicDTO that will be converted into an UHub.CoreLib.Entities.Users.User</param>
        public static explicit operator UHub.CoreLib.Entities.Users.User(UHub.CoreLib.Entities.Users.DTOs.User_C_PublicDTO nativeObj)
        {
            UHub.CoreLib.Entities.Users.User dtoObj = new UHub.CoreLib.Entities.Users.User();

            dtoObj.Email = nativeObj.Email;
            dtoObj.Username = nativeObj.Username;
            dtoObj.Password = nativeObj.Password;
            dtoObj.Name = nativeObj.Name;
            dtoObj.PhoneNumber = nativeObj.PhoneNumber;
            dtoObj.Major = nativeObj.Major;
            dtoObj.Year = nativeObj.Year;
            dtoObj.GradDate = nativeObj.GradDate;
            dtoObj.Company = nativeObj.Company;
            dtoObj.JobTitle = nativeObj.JobTitle;
            return dtoObj;
        }
    }


}

namespace UHub.CoreLib.Entities.Schools.DTOs
{
    ///<summary>
    ///AutoGenerated DataConverters for School_R_PublicDTO
    ///</summary>
    partial class School_R_PublicDTO
    {

        /// <summary>
        /// Convert School to School_R_PublicDTO
        /// </summary>
        /// <param name="arg1">The School that will be converted into an School_R_PublicDTO</param>
        public static explicit operator UHub.CoreLib.Entities.Schools.DTOs.School_R_PublicDTO(UHub.CoreLib.Entities.Schools.School dtoObj)
        {
            UHub.CoreLib.Entities.Schools.DTOs.School_R_PublicDTO nativeObj = new UHub.CoreLib.Entities.Schools.DTOs.School_R_PublicDTO();

            nativeObj.ID = dtoObj.ID;
            nativeObj.Name = dtoObj.Name;
            nativeObj.State = dtoObj.State;
            nativeObj.City = dtoObj.City;
            nativeObj.IsEnabled = dtoObj.IsEnabled;
            nativeObj.IsReadOnly = dtoObj.IsReadOnly;
            nativeObj.Description = dtoObj.Description;
            nativeObj.CreatedDate = dtoObj.CreatedDate;
            nativeObj.ModifiedDate = dtoObj.ModifiedDate;
            return nativeObj;
        }


        /// <summary>
        /// Convert School_R_PublicDTO to School
        /// </summary>
        /// <param name="arg1">The School_R_PublicDTO that will be converted into an UHub.CoreLib.Entities.Schools.School</param>
        public static explicit operator UHub.CoreLib.Entities.Schools.School(UHub.CoreLib.Entities.Schools.DTOs.School_R_PublicDTO nativeObj)
        {
            UHub.CoreLib.Entities.Schools.School dtoObj = new UHub.CoreLib.Entities.Schools.School();

            dtoObj.ID = nativeObj.ID;
            dtoObj.Name = nativeObj.Name;
            dtoObj.State = nativeObj.State;
            dtoObj.City = nativeObj.City;
            dtoObj.IsEnabled = nativeObj.IsEnabled;
            dtoObj.IsReadOnly = nativeObj.IsReadOnly;
            dtoObj.Description = nativeObj.Description;
            dtoObj.CreatedDate = nativeObj.CreatedDate;
            dtoObj.ModifiedDate = nativeObj.ModifiedDate;
            return dtoObj;
        }
    }


}

